### ISSUE TITLE
运行红屏错误

### ISSUE THREAD

**Issue by zj-insist** [CoderGLM/ReactNativeLeaning#1]
hi，
    我在运行Demo时候出现了一些问题，当环境和编译都配置好通过后，运行0.1和0.2的时候，会出现红屏错误，并有以下提示，暂时还未解决，不知道有没有什么解决方案，望收到回复
![image](https://cloud.githubusercontent.com/assets/18694979/21984645/db0cb274-dc31-11e6-96c7-2f6dd93b2878.png)

**Comment by CoderLim** [comment]
你好，把文件夹0.1NativeUIComponents重命名为NativeUIComponents（移除前面的序号），试一下。

**Comment by CoderLim** [comment]
@zj-insist 你好，把0.1NativeUIComponents重命名为NativeUIComponents（移除前面的需要），试一下。

**Comment by zj-insist** [comment]
已经解决了，需要先移除之前的node_module文件夹，然后重新下载依赖包，可能是以前的react native包有问题…

**Comment by CoderLim** [comment]
@zj-insist 👌
